language: c
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild denver-schedules-api.sln
  - nunit-console Schedules.API.Tests/bin/Debug/Schedules.API.Tests.dll
deploy:
  provider: heroku
  api_key:
    secure: TauFvTIpQb2y2yclPNDnYZx4p4jc3Cx398lirLdU40kMIEz4Pbe7JwGqw8Sq8jzlvxXvIB9QxaEyjZpFT8bsy01wC8ENC9VY2yomBs44kvkvMPDC7STyH4AT1bWjxQKtAshnEAi6DR3XAYlQS1N/JvHmO/NDzkphWv+NdIMPNOU=
  strategy: git
  app: staging-denver-now-api
  on:
    repo: codeforamerica/denver-schedules-api
