language: c
install:
- sudo apt-get install mono-devel mono-gmcs nunit-console
before_script:
- psql -f Database/run_all.sql -U postgres
script:
- xbuild denver-schedules-api.sln
- nunit-console Schedules.API.Tests/bin/Debug/Schedules.API.Tests.dll
addons:
  postgresql: '9.3'
deploy:
  provider: heroku
  api_key:
    secure: TauFvTIpQb2y2yclPNDnYZx4p4jc3Cx398lirLdU40kMIEz4Pbe7JwGqw8Sq8jzlvxXvIB9QxaEyjZpFT8bsy01wC8ENC9VY2yomBs44kvkvMPDC7STyH4AT1bWjxQKtAshnEAi6DR3XAYlQS1N/JvHmO/NDzkphWv+NdIMPNOU=
  strategy: git
  app: staging-denver-now-api
  on:
    repo: codeforamerica/denver-schedules-api
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/5410eca6-0a90-4bf0-b9c0-39f679940ba4/status
env:
- GEOSPATIAL_PROVIDER_NAME=Npgsql GEOSPATIAL_CONNECTION_STRING="Server=127.0.0.1;Port=5432;User Id=denver_schedules;Password=denver_schedules;Database=denver_schedules_development;"