## Travis CI Integration

language: c
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild denver-scheduling-api.sln
  ##- nunit-console Schedule.API/bin/Debug/ScheduleUnitTests.dll